title: William's Homepage
page-top-title: Pinrun Chen (William)
top-section-bg-text: William's Homepage
home-subtitle: Pinrun Chen &ensp;|&ensp; William
copyright-text: "&copy; Pinrun Chen 2023-2026. All Rights Reserved."
