title: William's Homepage
page-top-title: Pinrun Chen (William)
top-section-bg-text: William's Homepage
home-subtitle: 陈品润&ensp;|&ensp;Pinrun Chen (William)
copyright-text: "&copy; Pinrun Chen 2023-2025. All Rights Reserved."
